#!/bin/bash

# first create sessidlist.txt which is a list of all subjects
# type sessidlist after the command to feed list of subjects into the loop
sessidlist=$1
# in this case there are four separate runs of a task generated by selxavg3-sess -run-wise
runs='pr001 pr002 pr003 pr004'
# in this case there are four separate contrasts in a fear-conditioning paradigm
contrast='csp csm csp_v_csm csps'
# sets the subject space
subjects=$( cat $sessidlist )
echo $subjects
# sets the brain space
space='fc.lh fc.rh fc.mni305'
# identifies input path for cespct.nii.gz and cesvarpct.nii.gz
path2data=/group/tuominen/EmoSal/subjects/
# identifies output path for concatenated files
output=/group/tuominen/EmoSal/group/
# for all subjects specified in sessidlist.txt, concatenates cespct and cesvarpct files
for s in ${space[@]}; do

	for r in ${runs[@]}; do

		for c in ${contrast[@]}; do 

	
			pces=bold/${s}/${r}/${c}/cespct.nii.gz
			pcesvar=bold/${s}/${r}/${c}/cesvarpct.nii.gz

			cmd='mri_concat'
			for subj in ${subjects[@]}; do
					cmd+=" --i $path2data/${subj}/$pces"			
			done
			
			cmd+=" --o ${output}/${s}/${c}${r}/cespct.nii.gz"
			$cmd
			cmd='mri_concat'
			
			for subj in ${subjects[@]}; do
					cmd+=" --i $path2data/${subj}/$pcesvar"
			done
			
			cmd+=" --o ${output}/${s}/${c}${r}/cesvarpct.nii.gz"
			$cmd
		done 
	done 
done 
