#!/usr/bin/env python
# coding: utf-8

# In[2]:


#! /home/lauri/anaconda3/bin/python
# Load libraries
import os, sys, glob, re
import nibabel as nb
import pandas as pd
import numpy as np
from nilearn import plotting
import matplotlib.pyplot as plt
from surfer import Brain
from mayavi import mlab
mlab.init_notebook()


# In[3]:


def main():
# Visualize the left hemisphere activation map per run with Yeo 2011 overlay of functional connectivity maps
# State path to statistical mask files generated by freesurfer processes
    path = "/home/lauri/Documents/temp/"
    statpath = os.listdir(path)
    statfile = []
# Creates a function to grab all cortical statistical files 
    for s in statpath:
        if s.startswith('lh') and s.endswith('gz'):
            statfile.append(s)
    print('Making images for:')
    statfile.sort()
    print(statfile)
# Create the image using the plot_stat_map function
    for f in statfile:
        sig = os.path.join(path,f)
        sub = "fsaverage"
        hemi = "lh"
        surf = "inflated"
        view_types = ['lat','med']
        brain = Brain(sub, hemi, surf, cortex=None, background="midnightblue", views=view_types)
        overlay_file = sig
        brain.add_overlay(sig, min=1, max=3, name="ovrlay")
# To change colour of activations: note replace pos or neg: brain.overlays["ovrlay"].neg_bar.lut_mode = "winter"
        subjects_dir = os.environ["SUBJECTS_DIR"]
        annot_path = os.path.join(subjects_dir, sub, "label", "lh.Yeo2011_7Networks_N1000.annot")
        brain.add_annotation(annot_path, hemi='lh', borders=False, alpha=.33)
        brain.save_image(os.path.join(path,f + ".jpeg"))


# In[4]:


# Visualize the right hemisphere activation map per run with Yeo 2011 overlay of functional connectivity maps
# State path to statistical mask files generated by freesurfer processes
    path = "/home/lauri/Documents/temp/"
    statpath = os.listdir(path)
    statfile = []
# Creates a function to grab all cortical statistical files 
    for s in statpath:
        if s.startswith('rh') and s.endswith('gz'):
            statfile.append(s)
    print('Making images for:')
    statfile.sort()
    print(statfile)
# Create the image using the plot_stat_map function
    for f in statfile:
        sig = os.path.join(path,f)
        sub = "fsaverage"
        hemi = "rh"
        surf = "inflated"
        view_types = ['lat','med']
        brain = Brain(sub, hemi, surf, cortex=None, background="midnightblue",views=view_types)
        overlay_file = sig
        brain.add_overlay(sig, min=1, max=3, name="ovrlay")
# To change colour of activations: note replace pos or neg: brain.overlays["ovrlay"].neg_bar.lut_mode = "winter"
        subjects_dir = os.environ["SUBJECTS_DIR"]
        annot_path = os.path.join(subjects_dir, sub, "label", "rh.Yeo2011_7Networks_N1000.annot")
        brain.add_annotation(annot_path, hemi='rh', borders=False, alpha=.33)
        brain.save_image(os.path.join(path,f + ".jpeg"))
if __name__ == "__main__":
    # execute only if run as a script
    main()

